# Generated by Django 3.2.9 on 2021-12-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(verbose_name='comment_id')),
                ('name', models.TextField(verbose_name='name')),
                ('comment', models.TextField(verbose_name='comment')),
            ],
        ),
        migrations.CreateModel(
            name='contragents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contragent_id', models.IntegerField(verbose_name='contragent_id')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='danger_levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danger_id', models.IntegerField(verbose_name='danger_id')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('rules', models.TextField(verbose_name='rules')),
                ('color', models.TextField(verbose_name='color')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entity_id', models.IntegerField(verbose_name='Entity_id')),
                ('Position', models.TextField(verbose_name='position')),
                ('create_time', models.TimeField(verbose_name='create_time')),
                ('danger_id', models.IntegerField(verbose_name='danger_id')),
                ('area', models.FloatField(verbose_name='area')),
                ('status_id', models.IntegerField(verbose_name='status_id')),
                ('pipeline_id', models.IntegerField(verbose_name='pipeline_id')),
            ],
        ),
        migrations.CreateModel(
            name='Entity_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entity_id', models.IntegerField(verbose_name='Entity_id')),
                ('source_id', models.IntegerField(verbose_name='source_id')),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField(verbose_name='media_id')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='oil_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_company_id', models.IntegerField(verbose_name='oil_company_id')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='oil_pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_pipeline_id', models.IntegerField(verbose_name='oil_pipeline_id')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(verbose_name='source_id')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(verbose_name='status_id')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
    ]
